NurhakKayaSampleMvcApplication/Controllers/ShoppingCartController.cs
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5
        public ActionResult AddtoCart(int id)
        {
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);

            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5 
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            //Kullanıcıya doğrulama için sepetten çıkarılan albümün adı alınıyor
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            //Albüm sepetten çıkarılıyor
            int itemCount = cart.RemoveFromCart(id);

            //İşlem sonrası mesajı ekrana basmak için JSON nesnesi içeriği dolduruluyor
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    "has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary
        // ChildActionOnly attribute yapısı ile bu action'ın sadece bir partial view içinden çağrılmasını sağlamış oluyoruz. Bu sayede tarayıcı üzerinden bu şekilde action çağrılamaz:  /ShoppingCart/GenreMenu
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }

    }
}

NurhakKayaSampleMvcApplication/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;


namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            var genres = storeDB.Genres.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(string genre)
        {
            var genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        //
        //GET: /Store/Details/5
        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);

            return View(album);
        }

        //
        // GET: /Store/GenreMenu
        // ChildActionOnly attribute yapısı ile bu action'ın sadece bir partial view içinden çağrılmasını sağlamış oluyoruz. Bu sayede tarayıcı üzerinden bu şekilde action çağrılamaz:  /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }
    }
}

NurhakKayaSampleMvcApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>

</head>

<body>
    <div id="header">
        <h1><a href="/">Home Page | Nurhak's Music Store</a>


        </h1>
        <ul id="navlist">
            <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
            <li><a href="@Url.Content("~/Store/")">Store</a></li>
            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
            <li><a href="@Url.Content("~/StoreManager/")">Admin</a></li>
        </ul>
    </div>

    @{Html.RenderAction("GenreMenu", "Store");}
    <div id="main">
        @RenderBody()
    </div>

    <div id="footer">
        <div class="footer-social-media">
            <a class="twitter" href="https://twitter.com/nurhakka" title="Twitter" target="_blank">Twitter</a>
            <a class="facebook" href="https://www.facebook.com/nurhak.kaya.18" title="Facebook" target="_blank">Facebook</a>
            <a class="googleplus" href="https://plus.google.com/115234392828910400796/posts" title="Google Plus" target="_blank">Google Plus</a>
            <a class="linkedin" href="http://www.linkedin.com/pub/nurhak-kaya/51/250/538" title="LinkedIn" target="_blank">LinkedIn</a>
            <a class="blogger" href="http://nurhak-kaya.blogspot.com" title="Blogger" target="_blank">Blogger</a>
        </div>
        built by <a href="http://nurhakkaya.net" target="_blank">Nurhak Kaya - Software Engineer - MCSD - </a>
        <a href="http://nurhak-kaya.blogspot.com" target="_blank">Blogger</a>
    </div>
</body>
</html>